// Code generated by MDB Settings Generator. DO NOT EDIT.

package model

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	api "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/opensearch/v1/config"
	"github.com/yandex-cloud/terraform-provider-yandex/pkg/datasize"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

type AuditLog struct {
	ComplianceEnabled      types.Bool `tfsdk:"compliance_enabled"`
	LogRequestBody         types.Bool `tfsdk:"log_request_body"`
	LogSearchQueries       types.Bool `tfsdk:"log_search_queries"`
	LogDataModifications   types.Bool `tfsdk:"log_data_modifications"`
	LogIndexMetadataAccess types.Bool `tfsdk:"log_index_metadata_access"`
	LogMonitoringChecks    types.Bool `tfsdk:"log_monitoring_checks"`
	LogIndexMaintenance    types.Bool `tfsdk:"log_index_maintenance"`
	LogBackupOperations    types.Bool `tfsdk:"log_backup_operations"`
}

var AuditLogTypes = map[string]attr.Type{
	"compliance_enabled":        types.BoolType,
	"log_request_body":          types.BoolType,
	"log_search_queries":        types.BoolType,
	"log_data_modifications":    types.BoolType,
	"log_index_metadata_access": types.BoolType,
	"log_monitoring_checks":     types.BoolType,
	"log_index_maintenance":     types.BoolType,
	"log_backup_operations":     types.BoolType,
}

func auditLogToObject(ctx context.Context, cfg *api.AuditLog) (types.Object, diag.Diagnostics) {
	if cfg == nil {
		return types.ObjectNull(AuditLogTypes), nil
	}

	return types.ObjectValueFrom(ctx, AuditLogTypes, AuditLog{
		ComplianceEnabled:      types.BoolValue(cfg.GetComplianceEnabled().GetValue()),
		LogRequestBody:         types.BoolValue(cfg.GetLogRequestBody().GetValue()),
		LogSearchQueries:       types.BoolValue(cfg.GetLogSearchQueries().GetValue()),
		LogDataModifications:   types.BoolValue(cfg.GetLogDataModifications().GetValue()),
		LogIndexMetadataAccess: types.BoolValue(cfg.GetLogIndexMetadataAccess().GetValue()),
		LogMonitoringChecks:    types.BoolValue(cfg.GetLogMonitoringChecks().GetValue()),
		LogIndexMaintenance:    types.BoolValue(cfg.GetLogIndexMaintenance().GetValue()),
		LogBackupOperations:    types.BoolValue(cfg.GetLogBackupOperations().GetValue()),
	})
}

func PrepareCreateAuditLog(ctx context.Context, planObject types.Object) (*api.AuditLog, diag.Diagnostics) {
	plan := &AuditLog{}
	diags := planObject.As(ctx, plan, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, diags
	}

	res := &api.AuditLog{}

	if !(plan.ComplianceEnabled.IsUnknown() || plan.ComplianceEnabled.IsNull()) {
		res.ComplianceEnabled = &wrapperspb.BoolValue{Value: plan.ComplianceEnabled.ValueBool()}
	}

	if !(plan.LogRequestBody.IsUnknown() || plan.LogRequestBody.IsNull()) {
		res.LogRequestBody = &wrapperspb.BoolValue{Value: plan.LogRequestBody.ValueBool()}
	}

	if !(plan.LogSearchQueries.IsUnknown() || plan.LogSearchQueries.IsNull()) {
		res.LogSearchQueries = &wrapperspb.BoolValue{Value: plan.LogSearchQueries.ValueBool()}
	}

	if !(plan.LogDataModifications.IsUnknown() || plan.LogDataModifications.IsNull()) {
		res.LogDataModifications = &wrapperspb.BoolValue{Value: plan.LogDataModifications.ValueBool()}
	}

	if !(plan.LogIndexMetadataAccess.IsUnknown() || plan.LogIndexMetadataAccess.IsNull()) {
		res.LogIndexMetadataAccess = &wrapperspb.BoolValue{Value: plan.LogIndexMetadataAccess.ValueBool()}
	}

	if !(plan.LogMonitoringChecks.IsUnknown() || plan.LogMonitoringChecks.IsNull()) {
		res.LogMonitoringChecks = &wrapperspb.BoolValue{Value: plan.LogMonitoringChecks.ValueBool()}
	}

	if !(plan.LogIndexMaintenance.IsUnknown() || plan.LogIndexMaintenance.IsNull()) {
		res.LogIndexMaintenance = &wrapperspb.BoolValue{Value: plan.LogIndexMaintenance.ValueBool()}
	}

	if !(plan.LogBackupOperations.IsUnknown() || plan.LogBackupOperations.IsNull()) {
		res.LogBackupOperations = &wrapperspb.BoolValue{Value: plan.LogBackupOperations.ValueBool()}
	}

	return res, diag.Diagnostics{}
}

func PrepareUpdateAuditLog(ctx context.Context, planObject, stateObject types.Object) (*api.AuditLog, []string, diag.Diagnostics) {
	plan := &AuditLog{}
	state := &AuditLog{}
	updateMask := make([]string, 0)
	diags := planObject.As(ctx, plan, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, nil, diags
	}
	diags = stateObject.As(ctx, state, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, nil, diags
	}

	res := &api.AuditLog{}

	if !plan.ComplianceEnabled.IsUnknown() && !plan.ComplianceEnabled.Equal(state.ComplianceEnabled) {
		res.ComplianceEnabled = &wrapperspb.BoolValue{Value: plan.ComplianceEnabled.ValueBool()}
		updateMask = append(updateMask, "compliance_enabled")
	}

	if !plan.LogRequestBody.IsUnknown() && !plan.LogRequestBody.Equal(state.LogRequestBody) {
		res.LogRequestBody = &wrapperspb.BoolValue{Value: plan.LogRequestBody.ValueBool()}
		updateMask = append(updateMask, "log_request_body")
	}

	if !plan.LogSearchQueries.IsUnknown() && !plan.LogSearchQueries.Equal(state.LogSearchQueries) {
		res.LogSearchQueries = &wrapperspb.BoolValue{Value: plan.LogSearchQueries.ValueBool()}
		updateMask = append(updateMask, "log_search_queries")
	}

	if !plan.LogDataModifications.IsUnknown() && !plan.LogDataModifications.Equal(state.LogDataModifications) {
		res.LogDataModifications = &wrapperspb.BoolValue{Value: plan.LogDataModifications.ValueBool()}
		updateMask = append(updateMask, "log_data_modifications")
	}

	if !plan.LogIndexMetadataAccess.IsUnknown() && !plan.LogIndexMetadataAccess.Equal(state.LogIndexMetadataAccess) {
		res.LogIndexMetadataAccess = &wrapperspb.BoolValue{Value: plan.LogIndexMetadataAccess.ValueBool()}
		updateMask = append(updateMask, "log_index_metadata_access")
	}

	if !plan.LogMonitoringChecks.IsUnknown() && !plan.LogMonitoringChecks.Equal(state.LogMonitoringChecks) {
		res.LogMonitoringChecks = &wrapperspb.BoolValue{Value: plan.LogMonitoringChecks.ValueBool()}
		updateMask = append(updateMask, "log_monitoring_checks")
	}

	if !plan.LogIndexMaintenance.IsUnknown() && !plan.LogIndexMaintenance.Equal(state.LogIndexMaintenance) {
		res.LogIndexMaintenance = &wrapperspb.BoolValue{Value: plan.LogIndexMaintenance.ValueBool()}
		updateMask = append(updateMask, "log_index_maintenance")
	}

	if !plan.LogBackupOperations.IsUnknown() && !plan.LogBackupOperations.Equal(state.LogBackupOperations) {
		res.LogBackupOperations = &wrapperspb.BoolValue{Value: plan.LogBackupOperations.ValueBool()}
		updateMask = append(updateMask, "log_backup_operations")
	}

	return res, updateMask, diag.Diagnostics{}
}
