// Code generated by MDB Settings Generator. DO NOT EDIT.

package model

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	api "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/opensearch/v1/config"
	"github.com/yandex-cloud/terraform-provider-yandex/pkg/datasize"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

type OpenSearchConfig2 struct {
	MaxClauseCount         types.Int64  `tfsdk:"max_clause_count"`
	FielddataCacheSize     types.String `tfsdk:"fielddata_cache_size"`
	ReindexRemoteWhitelist types.String `tfsdk:"reindex_remote_whitelist"`
}

var openSearchConfig2Types = map[string]attr.Type{
	"max_clause_count":         types.Int64Type,
	"fielddata_cache_size":     types.StringType,
	"reindex_remote_whitelist": types.StringType,
}

func openSearchConfig2ToObject(ctx context.Context, cfg *api.OpenSearchConfig2) (types.Object, diag.Diagnostics) {
	if cfg == nil {
		return types.ObjectNull(openSearchConfig2Types), nil
	}

	return types.ObjectValueFrom(ctx, openSearchConfig2Types, OpenSearchConfig2{
		MaxClauseCount:         types.Int64Value(cfg.GetMaxClauseCount().GetValue()),
		FielddataCacheSize:     types.StringValue(cfg.GetFielddataCacheSize()),
		ReindexRemoteWhitelist: types.StringValue(cfg.GetReindexRemoteWhitelist()),
	})
}

func PrepareCreateOpenSearchConfig2(ctx context.Context, planObject types.Object) (*api.OpenSearchConfig2, diag.Diagnostics) {
	plan := &OpenSearchConfig2{}
	diags := planObject.As(ctx, plan, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, diags
	}

	res := &api.OpenSearchConfig2{}

	if !(plan.MaxClauseCount.IsUnknown() || plan.MaxClauseCount.IsNull()) {
		res.MaxClauseCount = &wrapperspb.Int64Value{Value: plan.MaxClauseCount.ValueInt64()}
	}

	if !(plan.FielddataCacheSize.IsUnknown() || plan.FielddataCacheSize.IsNull()) {
		res.FielddataCacheSize = plan.FielddataCacheSize.ValueString()
	}

	if !(plan.ReindexRemoteWhitelist.IsUnknown() || plan.ReindexRemoteWhitelist.IsNull()) {
		res.ReindexRemoteWhitelist = plan.ReindexRemoteWhitelist.ValueString()
	}

	return res, diag.Diagnostics{}
}

func PrepareUpdateOpenSearchConfig2(ctx context.Context, planObject, stateObject types.Object) (*api.OpenSearchConfig2, []string, diag.Diagnostics) {
	plan := &OpenSearchConfig2{}
	state := &OpenSearchConfig2{}
	updateMask := make([]string, 0)
	diags := planObject.As(ctx, plan, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, nil, diags
	}
	diags = stateObject.As(ctx, state, datasize.DefaultOpts)
	if diags.HasError() {
		return nil, nil, diags
	}

	res := &api.OpenSearchConfig2{}

	if !plan.MaxClauseCount.IsUnknown() && !plan.MaxClauseCount.Equal(state.MaxClauseCount) {
		res.MaxClauseCount = &wrapperspb.Int64Value{Value: plan.MaxClauseCount.ValueInt64()}
		updateMask = append(updateMask, "max_clause_count")
	}

	if !plan.FielddataCacheSize.IsUnknown() && !plan.FielddataCacheSize.Equal(state.FielddataCacheSize) {
		res.FielddataCacheSize = plan.FielddataCacheSize.ValueString()
		updateMask = append(updateMask, "fielddata_cache_size")
	}

	if !plan.ReindexRemoteWhitelist.IsUnknown() && !plan.ReindexRemoteWhitelist.Equal(state.ReindexRemoteWhitelist) {
		res.ReindexRemoteWhitelist = plan.ReindexRemoteWhitelist.ValueString()
		updateMask = append(updateMask, "reindex_remote_whitelist")
	}

	return res, updateMask, diag.Diagnostics{}
}
