// Code generated by tfgen. DO NOT EDIT.

package yandex_cloud_desktops_image

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	clouddesktop "github.com/yandex-cloud/go-genproto/yandex/cloud/clouddesktop/v1"
	apisdk "github.com/yandex-cloud/go-sdk/services/clouddesktop/v1/api"
	"github.com/yandex-cloud/terraform-provider-yandex/pkg/converter"
	"github.com/yandex-cloud/terraform-provider-yandex/pkg/validate"
	provider_config "github.com/yandex-cloud/terraform-provider-yandex/yandex-framework/provider/config"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
)

var _ datasource.DataSourceWithConfigure = (*yandexCloudDesktopsImageDataSource)(nil)

type yandexCloudDesktopsImageDataSource struct {
	providerConfig *provider_config.Config
}

func NewDataSource() datasource.DataSource {
	return &yandexCloudDesktopsImageDataSource{}
}

func (r *yandexCloudDesktopsImageDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "yandex_cloud_desktops_image"
}

func (r *yandexCloudDesktopsImageDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerConfig, ok := req.ProviderData.(*provider_config.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *provider_config.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.providerConfig = providerConfig
}

func (r *yandexCloudDesktopsImageDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = YandexCloudDesktopsImageDatasourceSchema(ctx)
}

func (r *yandexCloudDesktopsImageDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state yandexCloudDesktopsImageDatasourceModel
	diags := req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, timeoutInitError := state.Timeouts.Read(ctx, provider_config.DefaultTimeout)
	if timeoutInitError != nil {
		resp.Diagnostics.Append(timeoutInitError...)
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	reqApi := &clouddesktop.GetDesktopImageRequest{}
	reqApi.SetImageId(state.Id.ValueString())

	tflog.Debug(ctx, fmt.Sprintf("Read desktop_image request: %s", validate.ProtoDump(reqApi)))

	found := false
	folderID := converter.GetFolderID(state.FolderId.ValueString(), r.providerConfig, &resp.Diagnostics)
	var res *clouddesktop.DesktopImage
	if !(state.Name.IsNull() || state.Name.IsUnknown()) {
		res = readImageByNameAndFolderID(ctx, r.providerConfig.SDKv2, &diags, state.Name.ValueString(), folderID)
		if diags.HasError() {
			return
		}

		if res != nil {
			found = true
		}
	}

	if !found {
		var err error
		md := new(metadata.MD)
		res, err = apisdk.NewDesktopImageClient(r.providerConfig.SDKv2).Get(ctx, reqApi, grpc.Header(md))
		if traceHeader := md.Get("x-server-trace-id"); len(traceHeader) > 0 {
			tflog.Debug(ctx, fmt.Sprintf("Read desktop_image x-server-trace-id: %s", traceHeader[0]))
		}
		if traceHeader := md.Get("x-server-request-id"); len(traceHeader) > 0 {
			tflog.Debug(ctx, fmt.Sprintf("Read desktop_image x-server-request-id: %s", traceHeader[0]))
		}
		if err != nil {
			if validate.IsStatusWithCode(err, codes.NotFound) {
				resp.Diagnostics.AddWarning(
					"Failed to Read resource",
					"desktop_image not found",
				)
			} else {
				resp.Diagnostics.AddError(
					"Failed to Read resource",
					"Error while requesting API to get desktop_image:"+err.Error(),
				)
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("Read desktop_image response: %s", validate.ProtoDump(res)))

	if resp.Diagnostics.HasError() {
		return
	}

	// diagnostics don't have errors and resource is nil => resource not found
	if res == nil {
		resp.Diagnostics.AddWarning("Failed to read", "Resource not found")
		return
	}

	newState := flattenYandexCloudDesktopsImageDatasource(ctx, res, state, state.Timeouts, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &newState)...)
	if resp.Diagnostics.HasError() {
		return
	}
}
