// Code generated by tfgen. DO NOT EDIT.

package yandex_cloud_desktops_image

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func YandexCloudDesktopsImageDatasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description:         "A desktop image resource.",
		MarkdownDescription: "A desktop image resource.",
		Attributes: map[string]schema.Attribute{

			"folder_id": schema.StringAttribute{
				MarkdownDescription: "ID of the folder that the image belongs to.",
				Description: "ID of the folder that the image belongs to." +
					// proto paths: +
					// -> yandex.cloud.clouddesktop.v1.api.DesktopImage.folder_id
					"package: yandex.cloud.clouddesktop.v1.api\n" +
					"filename: yandex/cloud/clouddesktop/v1/desktop_image.proto\n",
				Optional: true,
				Computed: true,
			},

			"id": schema.StringAttribute{
				MarkdownDescription: "ID of the image to get.",
				Description: "ID of the image to get." +
					// proto paths: +
					// -> yandex.cloud.clouddesktop.v1.api.GetDesktopImageRequest.image_id
					"package: yandex.cloud.clouddesktop.v1.api\n" +
					"filename: yandex/cloud/clouddesktop/v1/desktop_image_service.proto\n",
				Optional: true,
				Computed: true,
			},

			"labels": schema.MapAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: "Description of the image.",
				Description: "Description of the image." +
					// proto paths: +
					// -> yandex.cloud.clouddesktop.v1.api.DesktopImage.labels
					"package: yandex.cloud.clouddesktop.v1.api\n" +
					"filename: yandex/cloud/clouddesktop/v1/desktop_image.proto\n",
				Computed: true,
			},

			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the image.",
				Description: "Name of the image." +
					// proto paths: +
					// -> yandex.cloud.clouddesktop.v1.api.DesktopImage.name
					"package: yandex.cloud.clouddesktop.v1.api\n" +
					"filename: yandex/cloud/clouddesktop/v1/desktop_image.proto\n",
				Computed: true,
				Optional: true,
				Validators: []validator.String{
					stringvalidator.ExactlyOneOf(
						path.MatchRoot("name"),
						path.MatchRoot("id"),
					),
				},
			},
			"timeouts": timeouts.AttributesAll(ctx),
		},

		Blocks: map[string]schema.Block{},
	}
}
