// Code generated by tfgen. DO NOT EDIT.

package yandex_cloud_desktops_image

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	clouddesktop "github.com/yandex-cloud/go-genproto/yandex/cloud/clouddesktop/v1"
)

type yandexCloudDesktopsImageDatasourceModel struct {
	FolderId types.String   `tfsdk:"folder_id"`
	Id       types.String   `tfsdk:"id"`
	Labels   types.Map      `tfsdk:"labels"`
	Name     types.String   `tfsdk:"name"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

func (m *yandexCloudDesktopsImageDatasourceModel) GetFolderId() types.String {
	return m.FolderId
}
func (m *yandexCloudDesktopsImageDatasourceModel) GetId() types.String {
	return m.Id
}
func (m *yandexCloudDesktopsImageDatasourceModel) GetLabels() types.Map {
	return m.Labels
}
func (m *yandexCloudDesktopsImageDatasourceModel) GetName() types.String {
	return m.Name
}

func NewYandexCloudDesktopsImageDatasourceModel() yandexCloudDesktopsImageDatasourceModel {
	return yandexCloudDesktopsImageDatasourceModel{
		FolderId: types.StringNull(),
		Id:       types.StringNull(),
		Labels:   types.MapNull(types.StringType),
		Name:     types.StringNull(),
	}
}

func yandexCloudDesktopsImageDatasourceModelFillUnknown(target yandexCloudDesktopsImageDatasourceModel) yandexCloudDesktopsImageDatasourceModel {
	if target.FolderId.IsUnknown() || target.FolderId.IsNull() {
		target.FolderId = types.StringNull()
	}
	if target.Id.IsUnknown() || target.Id.IsNull() {
		target.Id = types.StringNull()
	}
	if target.Labels.IsUnknown() || target.Labels.IsNull() {
		target.Labels = types.MapNull(types.StringType)
	}
	if target.Name.IsUnknown() || target.Name.IsNull() {
		target.Name = types.StringNull()
	}
	return target
}

var yandexCloudDesktopsImageDatasourceModelType = types.ObjectType{
	AttrTypes: map[string]attr.Type{
		"folder_id": types.StringType,
		"id":        types.StringType,
		"labels":    types.MapType{ElemType: types.StringType},
		"name":      types.StringType,
		"timeouts":  timeouts.AttributesAll(context.Background()).GetType(),
	},
}

func flattenYandexCloudDesktopsImageDatasource(ctx context.Context,
	yandexCloudDesktopsImageDatasource *clouddesktop.DesktopImage,
	state yandexCloudDesktopsImageDatasourceModel,
	to timeouts.Value,
	diags *diag.Diagnostics) types.Object {
	if yandexCloudDesktopsImageDatasource == nil {
		return types.ObjectNull(yandexCloudDesktopsImageDatasourceModelType.AttrTypes)
	}
	value, diag := types.ObjectValueFrom(ctx, yandexCloudDesktopsImageDatasourceModelType.AttrTypes, yandexCloudDesktopsImageDatasourceModel{
		FolderId: types.StringValue(yandexCloudDesktopsImageDatasource.GetFolderId()),
		Id:       types.StringValue(yandexCloudDesktopsImageDatasource.GetId()),
		Labels:   flattenYandexCloudDesktopsImageLabels(ctx, yandexCloudDesktopsImageDatasource.GetLabels(), state.Labels, diags),
		Name:     types.StringValue(yandexCloudDesktopsImageDatasource.GetName()),
		Timeouts: to,
	})
	diags.Append(diag...)
	return value
}

func expandYandexCloudDesktopsImageDatasource(ctx context.Context, yandexCloudDesktopsImageDatasourceState types.Object, diags *diag.Diagnostics) *clouddesktop.DesktopImage {
	if yandexCloudDesktopsImageDatasourceState.IsNull() || yandexCloudDesktopsImageDatasourceState.IsUnknown() {
		return nil
	}
	var yandexCloudDesktopsImageDatasource yandexCloudDesktopsImageDatasourceModel
	diags.Append(yandexCloudDesktopsImageDatasourceState.As(ctx, &yandexCloudDesktopsImageDatasource, basetypes.ObjectAsOptions{UnhandledNullAsEmpty: true, UnhandledUnknownAsEmpty: true})...)
	if diags.HasError() {
		return nil
	}
	return expandYandexCloudDesktopsImageDatasourceModel(ctx, yandexCloudDesktopsImageDatasource, diags)
}

func expandYandexCloudDesktopsImageDatasourceModel(ctx context.Context, yandexCloudDesktopsImageDatasourceState yandexCloudDesktopsImageDatasourceModel, diags *diag.Diagnostics) *clouddesktop.DesktopImage {
	value := &clouddesktop.DesktopImage{}
	value.SetFolderId(yandexCloudDesktopsImageDatasourceState.FolderId.ValueString())
	value.SetLabels(expandYandexCloudDesktopsImageLabels(ctx, yandexCloudDesktopsImageDatasourceState.Labels, diags))
	value.SetName(yandexCloudDesktopsImageDatasourceState.Name.ValueString())
	if diags.HasError() {
		return nil
	}
	return value
}

func flattenYandexCloudDesktopsImageLabels(ctx context.Context, yandexCloudDesktopsImageLabels map[string]string, listState types.Map, diags *diag.Diagnostics) types.Map {
	if yandexCloudDesktopsImageLabels == nil {
		if !listState.IsNull() && !listState.IsUnknown() && len(listState.Elements()) == 0 {
			return listState
		}
		return types.MapNull(types.StringType)
	}
	yandexCloudDesktopsImageLabelsValues := make(map[string]attr.Value)
	for k, elem := range yandexCloudDesktopsImageLabels {
		val := types.StringValue(elem)
		yandexCloudDesktopsImageLabelsValues[k] = val
	}

	value, diag := types.MapValue(types.StringType, yandexCloudDesktopsImageLabelsValues)
	diags.Append(diag...)
	return value
}

func expandYandexCloudDesktopsImageLabels(ctx context.Context, yandexCloudDesktopsImageLabelsState types.Map, diags *diag.Diagnostics) map[string]string {
	if yandexCloudDesktopsImageLabelsState.IsNull() || yandexCloudDesktopsImageLabelsState.IsUnknown() {
		return nil
	}
	if len(yandexCloudDesktopsImageLabelsState.Elements()) == 0 {
		return map[string]string{}
	}
	yandexCloudDesktopsImageLabelsRes := make(map[string]string)
	yandexCloudDesktopsImageLabelsType := make(map[string]types.String)
	diags.Append(yandexCloudDesktopsImageLabelsState.ElementsAs(ctx, &yandexCloudDesktopsImageLabelsType, false)...)
	if diags.HasError() {
		return nil
	}
	for k, elem := range yandexCloudDesktopsImageLabelsType {
		yandexCloudDesktopsImageLabelsRes[k] = elem.ValueString()
	}
	return yandexCloudDesktopsImageLabelsRes
}
