// Code generated by MDB Settings Generator. DO NOT EDIT.

package schema

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AuditLog() schema.SingleNestedAttribute {
	return schema.SingleNestedAttribute{
		MarkdownDescription: "OpenSearch audit logs settings.",
		Attributes:          AuditLogAttributes(),
		Optional:            true,
		Computed:            true,
	}
}

func AuditLogAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"compliance_enabled": schema.BoolAttribute{
			MarkdownDescription: "Enables audit logging on changes to a security index, such as changes to roles mappings and role creation or deletion.\nFor details, see [OpenSearch documentation](https://docs.opensearch.org/latest/security/audit-logs/index/#audit-user-account-manipulation).",
			Optional:            true,
			Computed:            true,
		},
		"log_request_body": schema.BoolAttribute{
			MarkdownDescription: "Includes the body of the request (if available) for both REST and the transport layer.\nFor details, see [OpenSearch documentation](https://docs.opensearch.org/latest/security/audit-logs/index/#disable-request-body-logging).",
			Optional:            true,
			Computed:            true,
		},
		"log_search_queries": schema.BoolAttribute{
			MarkdownDescription: "Enables indices data read requests logging.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_data_modifications": schema.BoolAttribute{
			MarkdownDescription: "Enables indices data write request logging.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_index_metadata_access": schema.BoolAttribute{
			MarkdownDescription: "Enables indices metadata requests logging.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_monitoring_checks": schema.BoolAttribute{
			MarkdownDescription: "Enables monitoring data requests logging.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_index_maintenance": schema.BoolAttribute{
			MarkdownDescription: "Enables indices maintenance requests logging, such as indices refreshes, flushes and merges.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_backup_operations": schema.BoolAttribute{
			MarkdownDescription: "Enables snapshots and repositories requests logging.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_authenticated_requests": schema.BoolAttribute{
			MarkdownDescription: "Enables logging of successfully authenticated REST requests.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_index_events": schema.BoolAttribute{
			MarkdownDescription: "Enables logging of index-level events, such as creating or deleting an index.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
		"log_bad_headers": schema.BoolAttribute{
			MarkdownDescription: "Enables logging of REST requests containing bad or spoofed security headers.\nFor details, see None.",
			Optional:            true,
			Computed:            true,
		},
	}
}
