//
// Create a new Lockbox Secret Version.
//
resource "yandex_lockbox_secret" "my_secret" {
  name = "test secret"
}

resource "yandex_lockbox_secret_version" "my_version" {
  secret_id = yandex_lockbox_secret.my_secret.id
  entries {
    key        = "key1"
    text_value = "value1" // explicit secret value
  }
  entries {
    key = "k2"
    // value generated by a command won't be visible in Terraform state
    command {
      path = "my_secret_generator.sh"
    }
  }
}
