# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - fix/runner-space

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Disk space before
        run: |
          df -h $GITHUB_WORKSPACE

      -
        name: CLEAN-UP
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

          # all of these default to true, but feel free to set to
          # false if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Disk space after CLEAN-UP
        run: |
          df -h $GITHUB_WORKSPACE
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Unshallow
#        run: git fetch --prune --unshallow
#      -
#        name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.21'
#      -
#        name: Import GPG key
#        id: import_gpg
#        uses: paultyng/ghaction-import-gpg@v2.1.0
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
#          PASSPHRASE: ""
#      -
#        name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v4
#        with:
#          version: '1.26'
#          args: release --rm-dist --timeout 45m
#        env:
#          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
